### ISSUE TITLE
Python 3 changes needed

### ISSUE THREAD

**Issue by waywardmonkeys** [dylan-lang/sphinx-extensions#11]
- `urlparse` is renamed to `urllib.parse`
- Can't `import drmindex` (but can `from dylandomain import drmindex` or `from . import drmindex`)
- `dict` merges for `option_spec` values doesn't work as is.

**Comment by cgay** [comment]
I suspect b647185f83ac6066fbb9497f6cd0d93b7448120b and a commit just before it fixed this.
